# Generated by Django 4.1.3 on 2022-12-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_New',
        ),
    ]
