# Generated by Django 4.1.3 on 2022-12-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_mrp_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_height',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='product',
            name='url_width',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(height_field='url_height', upload_to='photos/products', width_field='url_width'),
        ),
    ]
