version: "3"
services:
  django_app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: django_app:django
    container_name: django_container    
      
  nginx:
    build: ./nginx
    ports:
      -  "80:80"
    depends_on:
      - django_app